workflows:
  ios-workflow:
    name: "iOS Workflow"

    environment:
      flutter: stable  # إصدار Flutter المناسب
      xcode: latest    # إصدار Xcode المناسب
      ios_signing:
        distribution_type: app_store  # أو development إذا كنت تختبر
        bundle_identifier: com.elrawda.ios  # تأكد من تطابق Bundle ID مع تطبيقك

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install

      - name: Update iOS Deployment Target
        script: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 8.0/IPHONEOS_DEPLOYMENT_TARGET = 12.0/' ios/Runner.xcodeproj/project.pbxproj

      - name: Build iOS Archive
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/ios/iphoneos/Runner.xcarchive \
                     -allowProvisioningUpdates \
                     archive

      - name: Create IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath build/ios/iphoneos/Runner.xcarchive \
                     -exportOptionsPlist ios/Runner/Info.plist \
                     -exportPath build/ios/ipa \
                     -allowProvisioningUpdates

    artifacts:
      - build/ios/ipa/*.ipa  # تأكد من صحة المسار لتخزين ملف IPA

    publishing:
      email:
        recipients:
          - m7mdsonny@gmail.com  # أدخل بريدك الإلكتروني لتلقي إشعارات النجاح أو الفشل
