workflows:
  ios-workflow:
    name: iOS Build and Archive Workflow
    environment:
      flutter: stable  # يمكنك تعديل هذا إلى إصدار محدد من Flutter إذا لزم الأمر
    scripts:
      # 1. تثبيت التبعيات
      - name: Install dependencies
        script: |
          flutter pub get

      # 2. تعديل Podfile وتثبيت CocoaPods
      - name: Update Podfile and install CocoaPods
        script: |
          # تأكد من أن الحد الأدنى لإصدار iOS هو 12.0
          sed -i '' 's/platform :ios, '8.0'/platform :ios, '12.0'/g' ios/Podfile
          cd ios
          pod install
          cd ..

      # 3. بناء أرشيف iOS مع التوقيع التلقائي
      - name: Build iOS Archive
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/ios/iphoneos/Runner.xcarchive \
                     -allowProvisioningUpdates \
                     archive

      # 4. إنشاء ملف IPA
      - name: Create IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath build/ios/iphoneos/Runner.xcarchive \
                     -exportOptionsPlist ios/Runner/Info.plist \
                     -exportPath build/ios/ipa \
                     -allowProvisioningUpdates

    publishing:
      email:
        recipients:
          - m7mdsonny@gmail.com  # البريد الإلكتروني لتلقي الإشعارات
